# Generated by Django 2.2.7 on 2019-12-10 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BookManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
