# Generated by Django 2.2.7 on 2019-12-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManage', '0002_auto_20191210_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverImage',
            field=models.CharField(max_length=1500),
        ),
    ]
