# Generated by Django 2.2.7 on 2019-12-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManage', '0003_auto_20191210_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
