# Generated by Django 2.2.7 on 2019-12-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManage', '0004_auto_20191210_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverImage',
            field=models.CharField(max_length=1500),
        ),
    ]
